runtime: python311

handlers:
  - url: /
    static_files: dist/index.html
    secure: always
    upload: dist/index.html

  - url: /(.*)
    static_files: dist/\1
    secure: always
    upload: dist/(.*)